class AccessError(Execption): 
    pass

class ValueError(Execption):
    pass
    
